name: data_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  iconsax: ^0.0.8
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true


  fonts: 
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto_Condensed-Bold.ttf
        - asset: assets/fonts/Roboto_Condensed-Light.ttf
        - asset: assets/fonts/Roboto_Condensed-Regular.ttf
        - asset: assets/fonts/Roboto_Condensed-SemiBold.ttf


  assets:
    - assets/images/
